// <auto-generated />
using System;
using ExpenseTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414121420_AddUserRole")]
    partial class AddUserRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Api.Models.BillShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountOwed")
                        .HasColumnType("numeric");

                    b.Property<int>("MonthlyBillId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyBillId");

                    b.HasIndex("UserId");

                    b.ToTable("BillShares");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.MonthlyBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MonthYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionTemplateId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionTemplateId");

                    b.ToTable("MonthlyBills");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankTransactionRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BillShareId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiptImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("VerifiedAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankTransactionRef")
                        .IsUnique();

                    b.HasIndex("BillShareId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.SubscriptionParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultAmountOwed")
                        .HasColumnType("numeric");

                    b.Property<int>("SubscriptionTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("SubscriptionParticipants");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.SubscriptionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("BillingDayOfMonth")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("SubscriptionTemplates");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptPayId")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.BillShare", b =>
                {
                    b.HasOne("ExpenseTracker.Api.Models.MonthlyBill", "MonthlyBill")
                        .WithMany("BillShares")
                        .HasForeignKey("MonthlyBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyBill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.MonthlyBill", b =>
                {
                    b.HasOne("ExpenseTracker.Api.Models.SubscriptionTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("SubscriptionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Payment", b =>
                {
                    b.HasOne("ExpenseTracker.Api.Models.BillShare", "BillShare")
                        .WithOne("Payment")
                        .HasForeignKey("ExpenseTracker.Api.Models.Payment", "BillShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillShare");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.SubscriptionParticipant", b =>
                {
                    b.HasOne("ExpenseTracker.Api.Models.SubscriptionTemplate", "Template")
                        .WithMany("Participants")
                        .HasForeignKey("SubscriptionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Api.Models.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.SubscriptionTemplate", b =>
                {
                    b.HasOne("ExpenseTracker.Api.Models.User", "Admin")
                        .WithMany("AdminTemplates")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.BillShare", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.MonthlyBill", b =>
                {
                    b.Navigation("BillShares");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.SubscriptionTemplate", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.User", b =>
                {
                    b.Navigation("AdminTemplates");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
